### ISSUE TITLE
ng-dfp-ad-hide-when-empty doesn't work reliably

### ISSUE THREAD

**Issue by jinder** [ianmurrays/ngDfp#16]
I've noticed that 'ng-dfp-ad-hide-when-empty' doesn't correctly detect when the advert isn't visible.  I'm inspecting with the debug tools, and it still hides the div even when there is an advert inside.

**Comment by jinder** [comment]
Exposing .collapseEmptyDivs() may be easier?  https://support.google.com/dfp_premium/answer/3072674?hl=en

**Comment by ianmurrays** [comment]
I remember trying to use collapseEmptyDivs but it didn't work for me. If you can make it work let me know. :D

**Comment by jinder** [comment]
I've added googletag.pubads().collapseEmptyDivs(true); into the initialize method of the DoubleClickProvider and it seems to work for me.  Obviously if your outer container has a fixed height, it won't work.

Could you expose that as part of the provider?

**Comment by ceasbz** [comment]
@jinder You can try this way: `DoubleClickProvider.collapseEmptyDivs();`
