### ISSUE TITLE
Responsive Ads

### ISSUE THREAD

**Issue by anasqadrei** [ianmurrays/ngDfp#2]
My website is responsive and built using bootstrap 3.2. However I couldn't control the ads using ngDfp

This article suggest using multiple sizes
https://support.google.com/dfp_premium/answer/3423562?hl=en

But when I add this line in my angular code
```
DoubleClickProvider.defineSlot('/11xxx09/responsive_leaderboard', [[970, 90], [320, 50], [728, 90]], 'div-gpt-ad-14xxxxxxx51-0');
```
It always takes the first size ([970, 90] in that case).

How can I fix this? Does ngDfp support responsive ads or multiple ad sizes?

**Comment by mglaman** [comment]
This looks like it might be fairly easily to implement - https://support.google.com/dfp_premium/answer/3423562?hl=en

Come up with a way to define the sizeMapping()
````
var mapping = googletag.sizeMapping().
  addSize([1024, 768], [970, 250]).
  addSize([980, 690], [728, 90]).
  addSize([640, 480], [120, 60]).
  addSize([0, 0], [88, 31]).
  // Fits browsers of any size smaller than 640 x 480
  build();
````

Add it to the defineSlot() call.
````
gptAdSlots[1] = googletag.defineSlot('/123/sample/secondAd', [300, 250], 'ad-slot-2').
  defineSizeMapping(mapping2).
  setCollapseEmptyDiv(true).
  addService(googletag.pubads());
````

I'll see if I an whip something together.

**Comment by oitozero** [comment]
@anasqadrei @mglaman 
Just added support for Responsive Ads. Let me know if you have any feedback. 
https://github.com/ianmurrays/ngDfp/pull/11

**Comment by anasqadrei** [comment]
Yup, it's working fine now. But I have one point about the documentation. Before you call `defineSizeMapping`, you have to call `defineSlot` with an array of all the ad sizes that you are going to use. That's how it worked for me.
```
DoubleClickProvider.defineSlot('/123456/Your_Slot', [[970, 90], [728, 90], [88, 31]], 'div-gpt-ad-1234567890123-0');
DoubleClickProvider.defineSizeMapping('div-gpt-ad-1234567890123-0')
    .addSize([1024, 768], [970, 90])
    .addSize([980, 690], [728, 90])
    .addSize([640, 480], [728, 90])
    // Fits browsers of any size smaller than 640 x 480
    addSize([0, 0], [88, 31]);
```

**Comment by oitozero** [comment]
@anasqadrei Thanks for pointing that out. It will make documentation more clear. ;)
https://github.com/ianmurrays/ngDfp/pull/12

**Comment by anasqadrei** [comment]
Cheers :)
