### ISSUE TITLE
Support for enableSyncRendering()

### ISSUE THREAD

**Issue by indieocean** [ianmurrays/ngDfp#29]
Are you planning on adding support for Synchronous Request? 

Type: "Out Of Page" 

Ex. Mobile Adhesion Banner

**Comment by ianmurrays** [comment]
I'm not actively maintaining this library because I no longer use it in my projects, but I am receiving pull requests, so if you implement this please make a PR! :smile:

**Comment by indieocean** [comment]
Ok no problem! Thanks.

**Comment by indieocean** [comment]
It's going to be a pain to implement since those ads use document.write :-1:

**Comment by ianmurrays** [comment]
Ouch. Yeah. Sync stuff doesn't really feel right with Angular anyway (or the web for that matter :stuck_out_tongue: )

**Comment by indieocean** [comment]
We ended up creating directives for those ads and instead of using DFP templates we use our own client side :+1: Works like a charm!
