### ISSUE TITLE
Open Ad links in safari/chrome?

### ISSUE THREAD

**Issue by heartlandmedia** [ianmurrays/ngDfp#43]
When clicked it appears that my DFP ads are being opened in the inappBrowser and the user is not able to return to the app without closing and reopening. Is there any way to force ad links to be open by the default device browser?

**Comment by ianmurrays** [comment]
Sounds like a limitation of either the device or your app. I think you can intercept the link that's being opened in an in app browser and open it in safari (assuming it's your own app of course).
