### ISSUE TITLE
Inside ng-repeat

### ISSUE THREAD

**Issue by jinder** [ianmurrays/ngDfp#8]
Is there a way to get adverts to show if they're inside an ng-repeat/ng-if block?  I seem to consistently get black spaces at the moment.

**Comment by ianmurrays** [comment]
Never gave that a try. Are you sure you're using different tags for each ad in the repeat?

**Comment by guyyosan** [comment]
It's working for me, but after 30seconds when it supposed to refresh it disappears..
this is my html:

<div class="post-brick-ad margin-top-20" ng-if="index == 2">
    <div ng-dfp-ad="homePage1" ng-dfp-ad-refresh-interval="30000"></div>
</div>
<div class="post-brick-ad margin-top-20" ng-if="index == 6">
    <div ng-dfp-ad="homePage2" ng-dfp-ad-refresh-interval="30000"></div>
</div>
<div class="post-brick-ad margin-top-20" ng-if="index == 12">
    <div ng-dfp-ad="homePage3" ng-dfp-ad-refresh-interval="30000"></div>
</div>

**Comment by guyyosan** [comment]
got it to work with this code: (removed ng-dfp-ad-refresh-interval from the ads)
$rootScope.$on('$stateChangeStart', function(){
                    $interval.cancel(adsInterval);
                    $rootScope.state_loading = true;
                });

                $rootScope.$on('$stateChangeSuccess', function(){
                    $rootScope.state_loading = false;
                    adsInterval = $interval(function() {
                        DoubleClick
                            .getSlot('homePage1')
                            .then(function (slot) {
                                googletag.pubads().clear([slot]);
                            })
                            .getSlot('homePage2')
                            .then(function (slot) {
                                googletag.pubads().clear([slot]);
                            })
                            .getSlot('homePage3')
                            .then(function (slot) {
                                googletag.pubads().clear([slot]);
                            });
                        $timeout(function(){
                            DoubleClick.refreshAds('homePage1', 'homePage2', 'homePage3');
                        },3000);
                    }, 30000);
                });
